//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#pragma warning(push)
#pragma warning(disable: 4100) // unreferenced formal parameter

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "RootPage.xaml.h"

void ::ModelViewer::RootPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///RootPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::ModelViewer::RootPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
    case 1:
        {
            this->NavView = safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(this->NavView))->ItemInvoked += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewItemInvokedEventArgs^>(this, (void (::ModelViewer::RootPage::*)
                (::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewItemInvokedEventArgs^))&RootPage::NavView_ItemInvoked);
            (safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(this->NavView))->SelectionChanged += ref new ::Windows::Foundation::TypedEventHandler<::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewSelectionChangedEventArgs^>(this, (void (::ModelViewer::RootPage::*)
                (::Windows::UI::Xaml::Controls::NavigationView^, ::Windows::UI::Xaml::Controls::NavigationViewSelectionChangedEventArgs^))&RootPage::NavView_SelectionChanged);
            (safe_cast<::Windows::UI::Xaml::Controls::NavigationView^>(this->NavView))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ModelViewer::RootPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&RootPage::NavView_Loaded);
        }
        break;
    case 2:
        {
            this->ASB = safe_cast<::Windows::UI::Xaml::Controls::AutoSuggestBox^>(__target);
        }
        break;
    case 3:
        {
            ::Windows::UI::Xaml::Controls::AppBarButton^ element3 = safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::AppBarButton^>(element3))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ModelViewer::RootPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&RootPage::ImportClick);
        }
        break;
    case 4:
        {
            this->MoreInfoBtn = safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(__target);
            (safe_cast<::Windows::UI::Xaml::Controls::HyperlinkButton^>(this->MoreInfoBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::ModelViewer::RootPage::*)
                (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&RootPage::MoreInfoBtn_Click);
        }
        break;
    case 5:
        {
            this->ContentFrame = safe_cast<::Windows::UI::Xaml::Controls::Frame^>(__target);
        }
        break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::ModelViewer::RootPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}

#pragma warning(pop)


